apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: adjust-tz-example-cfg
  labels:
    app: adjust-tz
webhooks:
  - name: adjust-tz.k8s.example.io
    clientConfig:
      service:
        name: adjust-tz-example
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        adjust-tz: enabled
